#!/bin/bash
#
# Check Find My Mac v1.0
# By Daniel Demby
# heliomass@gmail.com
# http://heliomass.com
#
# Alerts you if Find My Mac is disabled, perhaps due to resetting NVRAM.

# Don't change these!
export VERSION='1.0'; # Script version

USE_GROWL=0

# Mac only
function check_osx() {

	if [ "$(uname)" == 'Darwin' ]; then
		return 0
	else
		return 1
	fi

}

# Dependencies
function check_deps() {

	local __missing_dep=0

	if [ -z "$(which nvram)" ]; then
		echo 'Missing nvram.' >&2
		__missing_dep=1
	fi
	if [ $USE_GROWL -eq 1 -a -z "$(which growlnotify)" ]; then
		echo 'Missing growlnotify.' >&2
		__missing_dep=1
	fi

	return $__missing_dep

}

# Help
function display_help() {

	echo ''
	echo "Check Find My Mac v${VERSION}"
	echo ''
	echo '--help'
	echo '   Display this help screen.'
	echo ''
	echo '--growl'
	echo '   Use growlnotify to display a notification message'
	echo '   if Find My Mac is switched off.'
	echo ''

}

# Parse command arguments
while [ $# -gt 0 ]; do
	case "$1" in
		--growl)
			USE_GROWL=1
			shift
			;;
		--help|-h|-?)
			display_help
			exit 0
			;;
		*)
			echo "Unrecognised paramter ${1}. Please use the --help switch to see usage." >&2
			exit 1
			;;
	esac
done

# Check we're running on a Mac.
check_osx
if [ $? -ne 0 ]; then
	echo 'This script will only function under OS X.' >&2
	exit 1
fi

# Check dependencies
check_deps
if [ $? -ne 0 ]; then
	exit 1
fi

# Check if Find My Mac is enabled.
nvram -p | grep mm-mobileme-token-FMM > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo 'Find My Mac may not be enabled.'
	if [ $USE_GROWL -eq 1 ]; then
		growlnotify --name 'Find My Mac' --message 'Find My Mac may not be switched on.'
	fi
else
	echo 'Find My Mac is enabled.'
fi
